### ISSUE TITLE
Test and increase SPI bitrate for the EPS sensors

### ISSUE THREAD

**Issue by PatrickKa** [SpaceTeam/STS1_COBC_SW#246]
Description

According to the datasheets, the maximum bitrates for the SPI interfaces are:

- STM32F411RE: FRAM & EPS SPI = SPI3: 25 Mbit/s
- EPS sensors: ???

Since the FRAM and EPS sensors share the same SPI, we either need to use the lower of the two bitrates or change the bitrate depending on which peripheral we talk with.

**Comment by PatrickKa** [comment]
Blocked by #77

**Comment by danielschloms** [comment]
From #211:
> EPS 2.0 uses [MAX11632EEG+T](https://data.space.tuwien.ac.at/index.php/f/1229331) as ADCs.

These ADCs support speeds up to 10 MHz, according to the Datasheet. The problem with switching baudrates is that the baudrate of the first `RODOS::HAL_SPI()` loses its configuration, since the `HW_HAL_SPI()` the context points to is overwritten.

`context = new (&SPIcontextArray[idx - 1]) HW_HAL_SPI(idx,sckPin,misoPin,mosiPin, nssPin);`

Furthermore, changing the baudrate + associated read/write would need to be protected by mutex. Changing the baudrate itself is provided by RODOS (`HAL_SPI::config()`). Setting it would probably need to be done in our `hal::Read()/Write()`.

Some possible solutions are:
- Another wrapper (now totaling **4(!)** layers of abstraction over HW, including the STM library)
- Changing the baudrate by hand / as a parameter for Write/Read (yuck)
- Changing the `RODOS::HAL_SPI()` to hold the baudrate (probably one of the saner options)

Even though the changes would be easy to implement, they introduce a lot of ugliness. Hence, I would prefer the option to lower the baudrate if the speed is still acceptable.

**Comment by PatrickKa** [comment]
We chose the simple solution of using the same baud rate for both EPS and FRAM communication in #252.

**Comment by PatrickKa** [comment]
@danielschloms tested communicating with the ADCs on the EPS as part of #258, and it worked → this issue is completed.
